config/routes.rb
HerbalCRM::Application.routes.draw do
  resources :notes

  devise_for :users

  mount WillFilter::Engine => "/will_filter"

  get "scheduled_messages/send_all"

  get "dashboard/index"

  resources :text_models

  resources :histories

  resources :messages

  resources :campaigns

  resources :mail_sequences

  resources :accounts

  resources :leads do
    put :assign_to, on: :member #not yet implemented
  end

  resources :lead_details

  resources :scheduled_messages

  root :to => 'leads#index'

  devise_for :users, :skip => [:registrations]
  resources :users, :except => [:show]

end

app/models/note.rb
class Note < ActiveRecord::Base
  order :id, :DESC
  belongs_to :lead
  belongs_to :user, :foreign_key => :assigned_to
  belongs_to :creator, :class_name => 'User', :foreign_key => :created_by

  before_validation lambda{ self.created_by = User.current_user.id }
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @notes }
    end
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
    @note = Note.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @note }
    end
  end

  # GET /notes/new
  # GET /notes/new.json
  def new
    @note = Note.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @note }
    end
  end

  # GET /notes/1/edit
  def edit
    @note = Note.find(params[:id])
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(params[:note])

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note.lead, notice: 'Note was successfully created.' }
        format.json { render json: @note, status: :created, location: @note }
      else
        format.html { render action: "new" }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /notes/1
  # PUT /notes/1.json
  def update
    @note = Note.find(params[:id])

    respond_to do |format|
      if @note.update_attributes(params[:note])
        format.html { redirect_to @note.lead, notice: 'Note was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note = Note.find(params[:id])
    @note.destroy

    respond_to do |format|
      format.html { redirect_to notes_url }
      format.json { head :ok }
    end
  end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.haml
= form_for @note, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :lead_id, :class => 'control-label'
    .controls
      = f.number_field :lead_id, :class => 'number_field'
  .control-group
    = f.label :created_by, :class => 'control-label'
    .controls
      = f.number_field :created_by, :class => 'number_field'
  .control-group
    = f.label :assigned_to, :class => 'control-label'
    .controls
      = f.number_field :assigned_to, :class => 'number_field'
  .control-group
    = f.label :due_date, :class => 'control-label'
    .controls
      = f.datetime_select :due_date, :class => 'datetime_select'
  .control-group
    = f.label :done, :class => 'control-label'
    .controls
      = f.check_box :done, :class => 'check_box'
  .control-group
    = f.label :text, :class => 'control-label'
    .controls
      = f.text_area :text, :class => 'text_area'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), notes_path, :class => 'btn'

app/views/notes/edit.html.haml
- model_class = Note
.page-header
  %h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/notes/index.html.haml
- model_class = Note
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:lead_id)
      %th= model_class.human_attribute_name(:created_by)
      %th= model_class.human_attribute_name(:assigned_to)
      %th= model_class.human_attribute_name(:due_date)
      %th= model_class.human_attribute_name(:done)
      %th= model_class.human_attribute_name(:text)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @notes.each do |note|
      %tr
        %td= link_to note.id, note_path(note)
        %td= note.lead_id
        %td= note.created_by
        %td= note.assigned_to
        %td= note.due_date
        %td= note.done
        %td= note.text
        %td=l note.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_note_path(note), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), note_path(note), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_note_path, :class => 'btn btn-primary'

app/views/notes/new.html.haml
- model_class = Note
.page-header
  %h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/notes/show.html.haml
- model_class = Note
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:lead_id) + ':'
  %br
  = @note.lead_id
%p
  %strong= model_class.human_attribute_name(:created_by) + ':'
  %br
  = @note.created_by
%p
  %strong= model_class.human_attribute_name(:assigned_to) + ':'
  %br
  = @note.assigned_to
%p
  %strong= model_class.human_attribute_name(:due_date) + ':'
  %br
  = @note.due_date
%p
  %strong= model_class.human_attribute_name(:done) + ':'
  %br
  = @note.done
%p
  %strong= model_class.human_attribute_name(:text) + ':'
  %br
  = @note.text

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), notes_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_note_path(@note), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), note_path(@note), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'