config/routes.rb
HerbalCRM::Application.routes.draw do
  resources :notes

  devise_for :users

  mount WillFilter::Engine => "/will_filter"

  get "scheduled_messages/send_all"

  get "dashboard/index"

  resources :text_models

  resources :histories

  resources :messages

  resources :campaigns

  resources :mail_sequences

  resources :accounts

  resources :leads do
    put :assign_to, on: :member #not yet implemented
  end

  resources :lead_details

  resources :scheduled_messages

  root :to => 'leads#index'

  devise_for :users, :skip => [:registrations]
  resources :users, :except => [:show]

end

app/models/lead.rb
class Lead < ActiveRecord::Base
  has_many :messages, :order => "date DESC", :dependent => :destroy
  has_many :scheduled_messages, :order => 'id DESC', :dependent => :destroy
  has_many :notes, :order => 'id DESC', :dependent => :destroy

  has_many :histories, :order => "created_at DESC", :dependent => :destroy
  has_many :lead_details, :dependent => :destroy, :dependent => :destroy
  belongs_to :account
  belongs_to :campaign
  belongs_to :user, :foreign_key => "assigned_to"

  after_save :send_mail_if_assigned

  accepts_nested_attributes_for :lead_details

  scope :to_reply, where(automatic: false).order("updated_at DESC")
  scope :automated, where(automatic: true, status: :attention_needed)

  STAGES = %w{lead prospect hot_lead ready_to_buy customer}
  STATUTES = %w{new attention_needed waiting_reply posponed discarted}

  def to_s
    return email if first_name.nil?
    "#{first_name} #{last_name}"
  end
  alias_method :name, :to_s

  # this creates the friendly url
  def to_param
    "#{id}-#{(email.sub('@','-at-')).parameterize}"
  end

  #### After Save
  def send_mail_if_assigned
    if assigned_to_changed?
      lead = self
      url = Rails.application.routes.url_helpers.lead_url(self,
              host: HerbalCRM::Application.config.action_mailer.default_url_options[:host])
      self.account.gmail.deliver! do
        to lead.user.email
        subject "HerbalCRM lead #{lead} has been assigned to you by #{User.current_user}"
        body "Please go to #{url}"
      end
    end
  end

  def process_automate
    return false if self.campaign.nil?

    next_message = self.campaign.mail_sequences.where(step: self.step, automatic: true).first
    if next_message
      ScheduledMessage.new(
          account_id: self.account_id,
          lead_id: self.id,
          to: self.email,
          subject: next_message.subject,
          body: next_message.body_text,
          body_html: next_message.body_html,
          scheduled: Time.now + next_message.send_after.to_i.minutes
      ).save
    else
      self.update_attribute :automatic, false
    end
  end

  def being_viewed_by_anyone_else?
    !viewing_by.nil? and viewing_by != User.current_user.id and (Time.now - last_access_time) < 1.hours
  end

  def set_access_by
    if viewing_by.nil? and (
        last_contacted.nil? or
        (Time.now - last_contacted) > 1.minutes or # message just sent
        (Time.now - last_access_time) > 1.hours # lot of time since last access
    )
      self.viewing_by = User.current_user.id
      self.last_access_time = Time.now
      save
    end
  end

  class << self
    # it's okey to have this here or should be made on each message received?
    def generate_automated_messages_for_all
      Lead.automated.each do |l|
        l.process_automate
      end
    end

    # User can be String (with email) or hash
    def make_from(lead, account = nil, campaign = nil)
      account = Account.find account if account.kind_of? Fixnum
      account = Account.first if account.nil?

      campaign = Campaign.find campaign if campaign.kind_of? Fixnum

      if lead.class == String
        lead = { email: lead }
      end

      lead[:account_id] = account.id
      lead[:campaign_id] = campaign.id unless campaign.nil?

      self.create lead
    end

    # Check if profile exist, and return it or create
    # user:string email
    def get_or_create(email, account = nil, campaign = nil, name = nil)
      if name.is_a? Hash
        # ToDo: more info suplied... fix array
      end

      logger.info " Buscando Lead #{name} <#{email}>"
      email = email.strip.downcase
      lead = self.find_by_email email

      params = {}
      if name
        name = name.strip.titleize.split(' ', 2)
        params[:first_name] = name.first
        params[:last_name] = name.last if (name.size == 2)
      end

      if lead.nil?
        puts " --> Creando Lead"
        lead = self.make_from(params.merge({email: email}), account, campaign)
      else
        lead.update_attributes(params) if lead.first_name.nil? && !name.nil?
        puts " --> Lead Existente (id: #{lead.id})"
      end

      lead
    end
  end
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
  # GET /leads
  # GET /leads.json
  def index
    #@leads = Lead.all
    #raise Filters::LeadFilter.inspect
    if params.empty? then
      params[:wf_order] = :created_at 
      params[:wf_per_page] = '100'
    end
    @leads= Lead.filter(:params => params, :filter => Filters::LeadFilter)
    @new_message = ScheduledMessage.new
    @campaigns = Campaign.all

    @text_models_per_campaign = {}
    @campaigns.each do |c|
      @text_models_per_campaign[c.id] = c.text_models.group_by(&:category).merge({'Global' => TextModel.global})
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @leads }
    end
  end

  # GET /leads/1
  # GET /leads/1.json
  def show
    @lead = Lead.find(params[:id])

    @lead.set_access_by

    # This was suggested on a forum with @lead.messages.build
    # Yaraher suggested to use build, but copy @lead.messages before
    #@new_message = @lead.scheduled_messages.build #ScheduledMessage.new(lead_id: @lead.id,
    @new_message = ScheduledMessage.new(lead_id: @lead.id, account_id: @lead.account_id)
    @new_note = Note.new(lead_id: @lead.id)

    @history = (@lead.messages + @lead.notes).sort_by(&:created_at).reverse

    @text_models = TextModel.all
    @text_models_select = {}
    @lead.campaign.all_text_models.each do |tm|
      @text_models_select[tm.category] ||= Array.new
      @text_models_select[tm.category] << tm
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @lead }
      format.js
    end
  end

  # GET /leads/new
  # GET /leads/new.json
  def new
    @lead = Lead.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @lead }
    end
  end

  # GET /leads/1/edit
  def edit
    @lead = Lead.find(params[:id])
  end

  # POST /leads
  # POST /leads.json
  def create
    @lead = Lead.new(params[:lead])

    respond_to do |format|
      if @lead.save
        format.html { redirect_to @lead, notice: 'Lead was successfully created.' }
        format.json { render json: @lead, status: :created, location: @lead }
      else
        format.html { render action: "new" }
        format.json { render json: @lead.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /leads/1
  # PUT /leads/1.json
  def update
    @lead = Lead.find(params[:id])

    respond_to do |format|
      if @lead.update_attributes(params[:lead])
        format.html { redirect_to @lead, notice: 'Lead was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @lead.errors, status: :unprocessable_entity }
      end
      format.js
    end
  end

  # DELETE /leads/1
  # DELETE /leads/1.json
  def destroy
    @lead = Lead.find(params[:id])
    @lead.destroy

    respond_to do |format|
      format.html { redirect_to leads_url }
      format.json { head :ok }
      format.js { head :ok }
    end
  end
end

app/helpers/leads_helper.rb
module LeadsHelper
  # Colors for use with bootstrap's labels
  STATUS_COLORS = {
      new: 'info',
      attention_needed: 'warning',
      waiting_reply: 'success',
      posponed: '', #default
      discarted: 'inverse'
  }
  def status_label (lead)
    "<span class='label label-#{STATUS_COLORS[lead.status.to_sym]}'>#{lead.status.humanize}</span>".html_safe
  end

  def time_ago time
    return t('Never') if time.nil?
    time_ago_in_words time
  end
end

app/views/leads/_form.html.haml
= form_for @lead, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :campaign_id, :class => 'control-label'
    .controls
      = f.number_field :campaign_id, :class => 'number_field'
  .control-group
    = f.label :account_id, :class => 'control-label'
    .controls
      = f.number_field :account_id, :class => 'number_field'
  .control-group
    = f.label :first_name, :class => 'control-label'
    .controls
      = f.text_field :first_name, :class => 'text_field'
  .control-group
    = f.label :last_name, :class => 'control-label'
    .controls
      = f.text_field :last_name, :class => 'text_field'
  .control-group
    = f.label :email, :class => 'control-label'
    .controls
      = f.text_field :email, :class => 'text_field'
  .control-group
    = f.label :status, :class => 'control-label'
    .controls
      = f.text_field :status, :class => 'text_field'
  .control-group
    = f.label :raiting, :class => 'control-label'
    .controls
      = f.number_field :raiting, :class => 'number_field'
  .control-group
    = f.label :phone, :class => 'control-label'
    .controls
      = f.text_field :phone, :class => 'text_field'
  .control-group
    = f.label :country, :class => 'control-label'
    .controls
      = f.text_field :country, :class => 'text_field'
  .control-group
    = f.label :city, :class => 'control-label'
    .controls
      = f.text_field :city, :class => 'text_field'
  .control-group
    = f.label :address, :class => 'control-label'
    .controls
      = f.text_field :address, :class => 'text_field'
  .control-group
    = f.label :source, :class => 'control-label'
    .controls
      = f.text_field :source, :class => 'text_field'
  .control-group
    = f.label :last_contacted, :class => 'control-label'
    .controls
      = f.datetime_select :last_contacted, :class => 'datetime_select'
  .control-group
    = f.label :step, :class => 'control-label'
    .controls
      = f.number_field :step, :class => 'number_field'
  .control-group
    = f.label :automatic, :class => 'control-label'
    .controls
      = f.check_box :automatic, :class => 'check_box'
  .control-group
    = f.label :messages_received_count, :class => 'control-label'
    .controls
      = f.number_field :messages_received_count, :class => 'number_field'
  .control-group
    = f.label :messages_sent_count, :class => 'control-label'
    .controls
      = f.number_field :messages_sent_count, :class => 'number_field'
  .control-group
    = f.label :resume, :class => 'control-label'
    .controls
      = f.text_area :resume, :class => 'text_area'
  .control-group
    = f.label :bounce, :class => 'control-label'
    .controls
      = f.number_field :bounce, :class => 'number_field'
  .control-group
    = f.label :stage, :class => 'control-label'
    .controls
      = f.text_field :stage, :class => 'text_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), leads_path, :class => 'btn'

app/views/leads/_history.html.haml
.container-fluid.content_history
  %div{id: "content#{@lead.id}", class: "my-content"}
    %ul{id: "tabs", class: "nav nav-tabs my-tabs", "data-tabs" => "tabs"}
      %li.active
        %a{"data-toggle" => "tab", :href => "#messages#{@lead.id}"} 
          %b Messages
      %li
        %a{"data-toggle" => "tab", :href => "#profile#{@lead.id}"} 
          %b Profile
        
    %div{id: "my-tab-content#{@lead.id}", class: "tab-content my-tab-content"}
      %div{id: "messages#{@lead.id}", class: "tab-pane active"}
        - @history.each do |item|
          - if item.kind_of? Note
            %div[item]{ :class => "alert alert-block" }
              %i{:style => "float: right; display: block"}= "-- by #{item.creator.name}"
              = item.text.html_safe
      
          - if item.kind_of? Message
            - message = item
            %div[message]{ :class => ('from_account' if message.from_account?) }
              %h3= message.subject
              %em{ alt: message.date }= time_ago message.date
              .from #{t 'From'}: #{message.from}
              - unless message.user.blank?
                .by #{t 'Written by'}: #{message.user}
              %pre= message.to_s.html_safe unless message.body.blank? || message.nil?
              = message.body_raw.html_safe if message.body.blank? && !message.body_raw.nil?
          %hr
      %div{id: "profile#{@lead.id}", class: "tab-pane"}
        = @lead.name
.close_box
  %button{class: "btn btn-danger",  type: "button"} X

        
      
  

app/views/leads/edit.html.haml
- model_class = @lead.class
.page-header
  %h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/leads/index.html.haml
- content_for :head do
  - aloha!

- model_class = Lead.new.class
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
  %em=raw(page_entries_info @leads)

%div= will_filter_tag(@leads)
//%div= will_filter_table_tag(@leads, columns: [])

%div{id: "leads_attention_needed"}
  %form.navbar-form
    // %input.span3{ id: 'search-models', type: :text, placeholder: 'Search...' }

  - @leads.each do |lead|
    %div[lead, :lead_box]
      %span.badge= lead.step
      %strong= link_to lead.name, lead_path(lead), rel: 'tooltip', title: lead.email
      %i.icon-chevron-right
      // %span.account= lead.account
      =campaign_label lead.campaign, lead.account.email
      %span.right= status_label lead
      - unless lead.user.nil?
        %i.icon-arrow-right
        %span.label.label-info= lead.user.name
      - if lead.being_viewed_by_anyone_else?
        .label.label-important
          %i.icon-eye-open
          #{User.find lead.viewing_by} since #{time_ago lead.last_access_time} ago
      .clear

      = time_ago lead.last_contacted
      .received #{t 'Messages Received'}: #{lead.messages_received_count}
      .sent #{t 'Messages Sent'}: #{lead.messages_sent_count}

      - message = lead.messages.first
      .message[message]
        .subject= message.subject unless message.blank? || message.body.blank?
        .msg= simple_format message.to_s.truncate(650) unless message.blank? || message.body.blank?
        %br
        %br
        = button_tag 'Response' , id: "response_button#{lead.id}", :class => 'btn btn-mini btn-primary response_button'
        = button_tag 'Fast Response', id: "response_button#{lead.id}", :class => 'btn btn-mini btn-primary fast_response_button'
        = link_to 'Detail', lead_path(lead), id: "detail#{lead.id}", :remote => true, class: "btn btn-mini btn-primary link_history"
        = link_to t('.destroy', :default => t("helpers.links.destroy")), lead_path(lead), :remote => true, :method => :delete, :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-mini btn-danger delete_lead'
        %div{id: "response#{lead.id}", class: "response"}
          %h2 Send Email
          - @new_message.lead_id = lead.id
          - @new_message.account_id = lead.account_id
          = form_for @new_message, remote: true do |f|
            = f.hidden_field :lead_id, value: lead.id
            = f.hidden_field :account_id, value: lead.account_id
            = f.hidden_field :to, value: lead.email
            = f.hidden_field :account_id, value: lead.account_id
            = f.hidden_field :user_id, value: current_user.id
            %b Schedule:
            = f.text_field :scheduled, value: Time.now
            %b Bcc:
            = f.text_field :bcc

            %div= f.text_field :subject, value: ("Re: #{lead.messages.first.subject}" unless lead.messages.empty?),
            class: 'span8'
            = f.text_area :body, value: lead.draft ,size: '150x3', placeholder: 'Reply here', class: 'span8 e-short-text', id: "textarea_body#{lead.id}"
            %div
              %select{class: "chzn text_model_title", rel: lead.id, name: "text_model[title]"}
                - @text_models_per_campaign[lead.campaign_id].each do |category, tms|
                  %optgroup{label:category}
                    - tms.each do |tm|
                      %option{value: tm.id}=tm.title
              %button{ class: "btn insert_text_model", rel: lead.id} Insert

            %div
              = f.submit 'Send', id: "button_send#{lead.id}", class: 'btn btn-success button_send'
              -#= button_tag 'Save Draft', class: 'btn savedraft', id: "savedraft#{lead.id}"
        %div{id: "fast_response#{lead.id}", class: "fast_response"}
          %br
          .navbar
            .navbar-inner
              - @text_models_per_campaign[lead.campaign.id].each do |name, data|
                - l = 'a'
                %h5=name
                - data.each do |text_model|
                  - @new_message.lead_id = lead.id
                  - @new_message.account_id = lead.account_id
                  .spanFormat
                    = form_for @new_message, remote: true do |f|
                      = f.hidden_field :lead_id, value: lead.id
                      = f.hidden_field :account_id, value: lead.account_id
                      = f.hidden_field :to, value: lead.email
                      = f.hidden_field :account_id, value: lead.account_id
                      = f.hidden_field :user_id, value: current_user.id
                      = f.hidden_field :scheduled, value: Time.now
                      = f.hidden_field :bcc
                      = f.hidden_field :subject, value: ("Re: #{lead.messages.first.subject}" unless lead.messages.empty?), class: 'span8'
                      = f.hidden_field :text_model_id, value: text_model.id
                      = f.submit text_model.title, id: "#{(text_model.title+ lead.name + l).gsub(/[^a-zA-Z]/, '') + lead.id.to_s}",  class: 'btn button_starred'
                      - l = l.next
        %br
        %br
        %div{id: "history#{lead.id}", class: "history", style: "display: none;"}
    %hr
= link_to t('.new', :default => t("helpers.links.new")), new_lead_path, :class => 'btn btn-primary'

= paginate @leads

app/views/leads/new.html.haml
- model_class = @lead.class
.page-header
  %h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/leads/show.html.haml
- content_for :head do
  - aloha!

.page-header
  %h1=@lead
  %div
    %span.badge= @lead.step
    = status_label @lead
    = time_ago @lead.last_contacted
    .btn-group
      %a.dropdown-toggle.btn.btn-mini{'data-toggle' => "dropdown", :href =>"#"}
        Search
        %span.caret
      %ul.dropdown-menu{:role => "menu",'aria-labelledby' => "dLabel"}
        %li= link_to 'Facebook', "https://www.facebook.com/search/results.php?q=#{u @lead.email}", target: '_blank'
        %li= link_to 'Google', "http://www.google.com/?q=#{u @lead.email}|#{u @lead.name}", target: '_blank'
        %li= link_to 'Gmail', "https://mail.google.com/mail/?shva=1#search/#{u @lead.email}/", target: '_blank'

- if @lead.being_viewed_by_anyone_else?
  .alert.alert-block
    This lead is being viewed by
    %b #{User.find @lead.viewing_by}
    since #{time_ago @lead.last_access_time} ago

= form_for(@lead, remote: true) do |f|
  .span6
    %p
      %strong #{t 'Campaign'}:
      = campaign_label @lead.campaign, @lead.account.email
    %p
      %strong #{t 'Email'}:
      = @lead.email
      %p
        %strong #{t 'Source'}:
        = @lead.source
    %p
      %strong #{t 'Messages Received'}:
      = @lead.messages_received_count
    %p
      %strong #{t 'Messages Sent'}:
      = @lead.messages_sent_count
    %p
      %strong #{t 'Automatic'}:
      = @lead.automatic
    %p
      %strong #{t 'Bounce'}:
      = @lead.bounce
  .span5
    .editable
      %strong #{t 'Phone'}:
      %span.static= @lead.phone
      = f.text_field :phone
    .editable
      %strong #{t 'Country'}:
      %span.static= @lead.country
      = f.text_field :country
    .editable
      %strong #{t 'City'}:
      %span.static= @lead.city
      = f.text_field :city
    .editable
      %strong #{t 'Address'}:
      %span.static= @lead.address
      = f.text_field :address
    .editable
      %strong #{t 'Stage'}:
      %span.static= @lead.stage
      = f.select :stage, Lead::STAGES, {:include_blank => true}
    .editable
      %strong #{t 'Status'}:
      %span.static= @lead.status
      = f.select :status, Lead::STATUTES
    .editable
      %strong #{t 'Raiting'}:
      %span.static= @lead.raiting
      = f.text_field :raiting, placeholder: 'From 1 to 5'

  %div{style: 'clear: both'}
  %strong Resume:
  %a.btn.btn-mini{id: 'btn-edit-resume'} Edit
  #leadResume= @lead.resume.to_s.html_safe
  = f.hidden_field :resume

  .form-actions
    = link_to t('Back'), leads_path, :class => 'btn'
    = link_to t('Edit'), edit_lead_path(@lead), :class => 'btn'
    = link_to t('Delete'), lead_path(@lead), :method => "delete", :confirm => 'Are you sure?',
    :class => 'btn btn-danger'
    %div{style: 'float: right;'}
      = f.hidden_field :draft
      %b Assign to:
      = f.collection_select(:assigned_to, User.all, :id, :name, { :prompt => 'Please assign to a user', :include_blank => true})
      %button{ type: "submit", class: "btn"} Assign

#reply

  %h2 Send Email
  = form_for @new_message do |f|
    = f.hidden_field :lead_id, value: @lead.id
    = f.hidden_field :account_id, value: @lead.account_id
    = f.hidden_field :to, value: @lead.email
    = f.hidden_field :account_id, value: @lead.account_id
    = f.hidden_field :user_id, value: current_user.id
    %b Schedule:
    = f.text_field :scheduled, value: Time.now
    %b Bcc:
    = f.text_field :bcc

    %div= f.text_field :subject, value: ("Re: #{@lead.messages.first.subject}" unless @lead.messages.empty?),
    class: 'span8'
    = f.text_area :body, value: @lead.draft ,size: '150x3', placeholder: 'Reply here',
        class: 'span8 editable-long-text'
    %div
      = f.submit 'Send', class: 'btn btn-success'
      = button_tag 'Save Draft', class: 'btn', id: 'savedraft'

  .navbar
    .navbar-inner
      %form.navbar-form
        // %input.span3{ id: 'search-models', type: :text, placeholder: 'Search...' }
        
        %select{class: 'chzn-select', id: 'text_model_title', name: 'text_model[title]'}
          - @text_models_select.each do |category, tms|
            %optgroup{label:category}
              - tms.each do |tm|
                %option{value: tm.id}=tm.title

        %button{ id: :insert_text_model, type: "submit", class: "btn"} Insert

  %h2 New Note
  = form_for @new_note do |f|
    %b Due Date:
    = f.hidden_field :lead_id, value: @lead.id
    = f.text_field :due_date
    = f.text_area :text, size: '150x3', class: 'span8 editable-short-text'
    = f.submit 'Add note', class: 'btn'

#scheduled_messages
  - @lead.scheduled_messages.each do |message|
    %div[message]{ :class => 'from_account'}
      %h3= message.subject
      -if message.sent?
        %span.label.label-warning Message sent
      -else
        %span.label.label-info Scheduled
        To send in:
        = (Time.now < message.scheduled) ? distance_of_time_in_words(Time.now, message.scheduled) : 'Next send'
      - unless message.user.blank?
        .by #{t 'Written by'}: #{message.user}
      - unless message.sent?
        = link_to "Edit", edit_scheduled_message_path(message)
        = link_to t('.destroy', :default => t("Delete")), scheduled_message_path(message), :method => :delete,
        :remote => true, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm",
        :default => 'Are you sure?')) }
      %pre= message.body
    %hr

#history
  - @history.each do |item|
    - if item.kind_of? Note
      %div[item]{ :class => "alert alert-block" }
        %i{:style => "float: right; display: block"}= "-- by #{item.creator.name}"
        = item.text.html_safe

    - if item.kind_of? Message
      - message = item
      %div[message]{ :class => ('from_account' if message.from_account?) }
        %h3= message.subject
        %em{ alt: message.date }= time_ago message.date
        .from #{t 'From'}: #{message.from}
        - unless message.user.blank?
          .by #{t 'Written by'}: #{message.user}
        %pre= message.to_s.html_safe unless message.body.blank? || message.nil?
        = message.body_raw.html_safe if message.body.blank? && !message.body_raw.nil?
    %hr

app/views/leads/show.js.erb
$('#history' + '<%= @lead.id %>').html("<%= escape_javascript(render :partial => "history", :locals => {:@history => @history, :@lead => @lead}).html_safe %>");

app/views/leads/update.js.erb
//alert("Done");

$.bootstrapGrowl("Action completed!", {
    type: 'info'
});