config/routes.rb
HerbalCRM::Application.routes.draw do
  resources :notes

  devise_for :users

  mount WillFilter::Engine => "/will_filter"

  get "scheduled_messages/send_all"

  get "dashboard/index"

  resources :text_models

  resources :histories

  resources :messages

  resources :campaigns

  resources :mail_sequences

  resources :accounts

  resources :leads do
    put :assign_to, on: :member #not yet implemented
  end

  resources :lead_details

  resources :scheduled_messages

  root :to => 'leads#index'

  devise_for :users, :skip => [:registrations]
  resources :users, :except => [:show]

end

app/models/text_model.rb
class TextModel < ActiveRecord::Base
  has_and_belongs_to_many :campaigns

  scope :starred, where(:starred => true)
  scope :global, where(:global => true)

  after_save :delete_associated_campaigns, :if => Proc.new {|tm| tm.global }

  def self.categories
    # @todo chache this
    group('category').select('category')
  end

  def from_category
    TextModel.where(category: self.category)
  end

  def delete_associated_campaigns
    campaigns.clear
  end


end

app/controllers/text_models_controller.rb
class TextModelsController < ApplicationController
  # GET /text_models
  # GET /text_models.json
  def index
    @text_models = TextModel.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @text_models }
    end
  end

  # GET /text_models/1
  # GET /text_models/1.json
  def show
    @text_model = TextModel.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @text_model }
    end
  end

  # GET /text_models/new
  # GET /text_models/new.json
  def new
    @text_model = TextModel.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @text_model }
    end
  end

  # GET /text_models/1/edit
  def edit
    @text_model = TextModel.find(params[:id])
  end

  # POST /text_models
  # POST /text_models.json
  def create
    @text_model = TextModel.new(params[:text_model])

    respond_to do |format|
      if @text_model.save
        format.html { redirect_to @text_model, notice: 'Text model was successfully created.' }
        format.json { render json: @text_model, status: :created, location: @text_model }
      else
        format.html { render action: "new" }
        format.json { render json: @text_model.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /text_models/1
  # PUT /text_models/1.json
  def update
    @text_model = TextModel.find(params[:id])

    respond_to do |format|
      if @text_model.update_attributes(params[:text_model])
        format.html { redirect_to @text_model, notice: 'Text model was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @text_model.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /text_models/1
  # DELETE /text_models/1.json
  def destroy
    @text_model = TextModel.find(params[:id])
    @text_model.destroy

    respond_to do |format|
      format.html { redirect_to text_models_url }
      format.json { head :ok }
    end
  end
end

app/helpers/text_models_helper.rb
module TextModelsHelper
end

app/views/text_models/_form.html.haml
- content_for :head do
  - aloha! extra_plugins: ['extra/comments']

= form_for @text_model, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :title, :class => 'control-label'
    .controls
      = f.text_field :title, :class => 'text_field'
  .control-group
    = f.label :body, :class => 'control-label'
    .controls
      = f.text_area :body, :class => 'text_area editable-long-text span8'
  .control-group
    = f.label :category, :class => 'control-label'
    .controls
      = f.text_field :category, :class => 'text_field'
  .control-group
    = f.label :starred, :class => 'control-label'
    .controls
      = f.check_box :starred
  .control-group
    = f.label 'Global Text Model (All campaigns)', :class => 'control-label'
    .controls
      = f.check_box :global
  .control-group
    = f.label :campaigns, :class => 'control-label'
    .controls
      = hidden_field_tag "text_model[campaign_ids][]", nil
      - Campaign.all.each do |campaign|
        %label.checkbox
          = check_box_tag "text_model[campaign_ids][]", campaign.id, @text_model.campaign_ids.include?(campaign.id),
          id: dom_id(campaign)
          = "#{campaign.name}"
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), text_models_path, :class => 'btn'

app/views/text_models/edit.html.haml
- model_class = TextModel
.page-header
  %h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/text_models/index.html.haml
- model_class = TextModel
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:title)
      %th= model_class.human_attribute_name(:category)
      %th= model_class.human_attribute_name(:global)
      %th= model_class.human_attribute_name(:body)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @text_models.each do |text_model|
      %tr
        %td= link_to text_model.title, edit_text_model_path(text_model)
        %td= text_model.category
        %td= 'SI' if text_model.global
        %td= truncate strip_tags(text_model.body), :length => 45
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_text_model_path(text_model), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), text_model_path(text_model), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_text_model_path, :class => 'btn btn-primary'

app/views/text_models/new.html.haml
- model_class = TextModel
.page-header
  %h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/text_models/show.html.haml
- model_class = TextModel
.page-header
  %h1=@text_model.title

%p
  %strong= model_class.human_attribute_name(:body) + ':'
  %br
  %div{style: 'border: 1px solid grey; padding: 4px;'}
    = @text_model.body.html_safe
%p
  %strong= model_class.human_attribute_name(:category) + ':'
  %br
  = @text_model.category

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), text_models_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_text_model_path(@text_model), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), text_model_path(@text_model), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'