config/routes.rb
HerbalCRM::Application.routes.draw do
  resources :notes

  devise_for :users

  mount WillFilter::Engine => "/will_filter"

  get "scheduled_messages/send_all"

  get "dashboard/index"

  resources :text_models

  resources :histories

  resources :messages

  resources :campaigns

  resources :mail_sequences

  resources :accounts

  resources :leads do
    put :assign_to, on: :member #not yet implemented
  end

  resources :lead_details

  resources :scheduled_messages

  root :to => 'leads#index'

  devise_for :users, :skip => [:registrations]
  resources :users, :except => [:show]

end

app/models/scheduled_message.rb
class ScheduledMessage < ActiveRecord::Base
  belongs_to :account
  belongs_to :lead
  belongs_to :user
  order :scheduled, 'DESC'

  DEFAULT_SCHEDULE_TIME = 15.minutes
  before_create :set_default_data
  after_create :update_lead_details

  before_save :set_html_and_plain, :update_text_model

  scope :to_send, where(:sent => false).where("scheduled < ?", Time.now)

  def to_s
    "#{self.subject} to: #{self.to}"
  end

  def sent?
    self.sent
  end

  def set_html_and_plain
    unless self.body_html
      self.body_html = body
      self.body = html_to_text(body_html)
    end
  end

  # Update lead details while creating the sm
  def update_lead_details
    self.lead.update_attributes({
        :status           => :waiting_reply,
        :last_contacted   => self.created_at, #Time.now,
        :viewing_by       => nil
    })
  end

  def update_text_model
    self.body = self.body.gsub("{lead.name}", self.lead.name)
    self.body_html = self.body_html.gsub("{lead.name}", self.lead.name)
  end

  def self.send_all
    self.to_send.limit(15).each { |sm| sm.send_msg }
  end

  def send_msg
    puts " * Sending: #{self}"
    begin
      message = self
      m = self.account.gmail.deliver! do
        to message.to
        bcc message.bcc unless message.bcc.blank?
        subject message.subject

        #maybe this is throwing an error?
        text_part do
          content_type "text/plain; charset=utf-8"
          body message.body
        end
        html_part do
          content_type 'text/html; charset=UTF-8'
          body message.body_html + "<br/><br/>" + message.account.signature
        end
      end

      self.update_attributes! sent: true, message_id: m.message_id
      puts "\e[32m[OK]\e[0m"
    rescue Exception => e
      puts "\e[31m[!]\e[0m Error sending email"
      puts e.message
      #puts e.backtrace
    end
  end

  private
  def set_default_data
    self.scheduled = DEFAULT_SCHEDULE_TIME.from_now if self.scheduled.nil?
  end
end

app/controllers/scheduled_messages_controller.rb
class ScheduledMessagesController < ApplicationController
  def send_all
    ScheduledMessage.send_all
    raise "OK"
  end

  def index
    @scheduled_messages = ScheduledMessage.where(:sent => false)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @scheduled_messages }
    end
  end

  def edit
    @scheduled_message = ScheduledMessage.find(params[:id])
    if @scheduled_message.sent?
      redirect_to scheduled_messages_url, notice: 'This message was already sent and cant be edited'
    end
  end

  def update
    @scheduled_message = ScheduledMessage.find(params[:id])

    respond_to do |format|
      if @scheduled_message.update_attributes(params[:scheduled_message])
        format.html { redirect_to lead_url(@scheduled_message.lead), notice: 'Scheduled Message was successfully
updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @scheduled_message.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @scheduled_message = ScheduledMessage.find(params[:id])
    lead = @scheduled_message.lead
    @scheduled_message.destroy

    respond_to do |format|
      format.html { redirect_to lead_url(lead) }
      format.json { head :ok }
      format.js
    end
  end

  def create
    if params[:scheduled_message][:text_model_id]
      params[:scheduled_message][:body] = TextModel.find(params[:scheduled_message][:text_model_id]).body
      params[:scheduled_message].except! :text_model_id
    end
    @scheduled_message = ScheduledMessage.new(params[:scheduled_message])

    respond_to do |format|
      if @scheduled_message.save
        # If we manually create a scheduled message we change automated to false
        @scheduled_message.lead.update_attributes automatic: false

        format.html { redirect_to @scheduled_message.lead, notice: 'Message was successfully scheduled.' }
        format.json { render json: @scheduled_message, status: :created, location: @scheduled_message }
        format.js
      else
        format.html { render action: "new" }
        format.json { render json: @scheduled_message.errors, status: :unprocessable_entity }
      end
    end
  end

end

app/helpers/scheduled_messages_helper.rb
module ScheduledMessagesHelper
end

app/views/scheduled_messages/_form.html.haml
= form_for @scheduled_message, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :account_id, :class => 'control-label'
    .controls
      = f.number_field :account_id, :class => 'number_field'
  .control-group
    = f.label :lead_id, :class => 'control-label'
    .controls
      = f.number_field :lead_id, :class => 'number_field'
  .control-group
    = f.label :to, :class => 'control-label'
    .controls
      = f.text_field :to, :class => 'text_field'
  .control-group
    = f.label :cc, :class => 'control-label'
    .controls
      = f.text_field :cc, :class => 'text_field'
  .control-group
    = f.label :bcc, :class => 'control-label'
    .controls
      = f.text_field :bcc, :class => 'text_field'
  .control-group
    = f.label :subject, :class => 'control-label'
    .controls
      = f.text_field :subject, :class => 'text_field'
  .control-group
    = f.label :body, :class => 'control-label'
    .controls
      = f.text_area :body, :class => 'text_area'
  .control-group
    = f.label :body_html, :class => 'control-label'
    .controls
      = f.text_area :body_html, :class => 'text_area'
  .control-group
    = f.label :scheduled, :class => 'control-label'
    .controls
      = f.datetime_select :scheduled, :class => 'datetime_select'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("Cancel")), scheduled_messages_path, :class => 'btn'
    = link_to t('.destroy', :default => t("Destroy")), scheduled_message_path(@scheduled_message), :method => :delete,
     :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/scheduled_messages/destroy.js.erb
$('#<%= dom_id(@scheduled_message) %>').fadeOut();

app/views/scheduled_messages/edit.html.haml
- model_class = ScheduledMessage
.page-header
  %h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/scheduled_messages/index.html.haml
- model_class = ScheduledMessage
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:account_id)
      %th= model_class.human_attribute_name(:lead_id)
      %th= model_class.human_attribute_name(:subject)
      %th= model_class.human_attribute_name(:scheduled)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @scheduled_messages.each do |scheduled_message|
      %tr
        %td= scheduled_message.account
        %td
          = scheduled_message.lead
          = scheduled_message.to
          = scheduled_message.bcc
        %td= scheduled_message.subject
        %td= scheduled_message.scheduled
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_scheduled_message_path(scheduled_message), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), scheduled_message_path(scheduled_message), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_scheduled_message_path, :class => 'btn btn-primary'

app/views/scheduled_messages/new.html.haml
- model_class = ScheduledMessage
.page-header
  %h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/scheduled_messages/send_all.html.haml
%h1 ScheduledMessages#send_all
%p Find me in app/views/scheduled_messages/send_all.html.haml

app/views/scheduled_messages/show.html.haml
- model_class = ScheduledMessage
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:account_id) + ':'
  %br
  = @scheduled_message.account_id
%p
  %strong= model_class.human_attribute_name(:lead_id) + ':'
  %br
  = @scheduled_message.lead_id
%p
  %strong= model_class.human_attribute_name(:to) + ':'
  %br
  = @scheduled_message.to
%p
  %strong= model_class.human_attribute_name(:cc) + ':'
  %br
  = @scheduled_message.cc
%p
  %strong= model_class.human_attribute_name(:bcc) + ':'
  %br
  = @scheduled_message.bcc
%p
  %strong= model_class.human_attribute_name(:subject) + ':'
  %br
  = @scheduled_message.subject
%p
  %strong= model_class.human_attribute_name(:body) + ':'
  %br
  = @scheduled_message.body
%p
  %strong= model_class.human_attribute_name(:body_html) + ':'
  %br
  = @scheduled_message.body_html
%p
  %strong= model_class.human_attribute_name(:scheduled) + ':'
  %br
  = @scheduled_message.scheduled
%p
  %strong= model_class.human_attribute_name(:sent) + ':'
  %br
  = @scheduled_message.sent
%p
  %strong= model_class.human_attribute_name(:message_id) + ':'
  %br
  = @scheduled_message.message_id

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), scheduled_messages_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_scheduled_message_path(@scheduled_message), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), scheduled_message_path(@scheduled_message), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'